version: 2.1


jobs:
  build-dockerfile:
    docker:
      - image: cimg/base:2022.04
    parameters:
      image-name:
        description: Image name
        type: string
      image-tag:
        description: Image tag
        type: string
      target:
        description: Dockerfile target
        type: string
        default: ""
      dockerfile:
        description: Dockerfile to use
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t "ethereumoptimism/<<parameters.image-name>>:<<parameters.image-tag>>" -f <<parameters.dockerfile>> <<#parameters.target>>--target <<parameters.target>><</parameters.target>> .
            docker push "ethereumoptimism/<<parameters.image-name>>:<<parameters.image-tag>>"

workflows:
  main:
    jobs:
      - build-dockerfile:
          context:
            - optimism
          filters:
            branches:
              only:
                - main
          image-name: op-node
          image-tag: develop
          dockerfile: ops-bedrock/Dockerfile.node
          name: Build op-node
      - build-dockerfile:
          context:
            - optimism
          filters:
            branches:
              only:
                - main
          image-name: op-proposer
          image-tag: develop
          dockerfile: ops-bedrock/Dockerfile.proposer
          name: Build op-proposer
      - build-dockerfile:
          context:
            - optimism
          filters:
            branches:
              only:
                - main
          image-name: op-batcher
          image-tag: develop
          dockerfile: ops-bedrock/Dockerfile.batcher
          name: Build op-batcher
