FROM golang:1.18.0-alpine3.15 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY go.mod /app/go.mod
COPY go.sum /app/go.sum

WORKDIR /app
RUN go mod download -x

COPY Makefile /app/Makefile
COPY ./opnode /app/opnode

RUN make opnode

FROM alpine:3.15

COPY --from=builder /app/bin/op /usr/local/bin

CMD ["op"]
