#FROM ethereumoptimism/reference-optimistic-geth:latest
FROM inphi/reference-optimistic-geth:latest

RUN apk add --no-cache jq

COPY entrypoint.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
