name: Devnet integration tests

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'feat/*'
  pull_request:
  workflow_dispatch:

jobs:
  compose-devnet:
    runs-on: ubuntu-latest
    name: Run integration tests on devnet
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - run: cd packages/contracts && yarn install && yarn build
      - run: cd packages/integration-tests && yarn install && yarn build:contracts

      - run: make devnet-up
        name: Bring up the stack

      - run: sleep 10 && docker ps && make integration-tests
