name: Contracts lint, test and static analysis

on:
  push:
    branches:
      - 'main'
      - 'staging'
  pull_request:
  workflow_dispatch:

env:
  PYTEST_ADDOPTS: "--color=yes"

defaults:
    run:
      shell: bash
      working-directory: ./packages/contracts

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Install and Build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
            node-version: '14'
            cache: 'yarn'
      - run: yarn install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Yarn Build
        run: yarn build

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Lint
        run: yarn lint:check

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Test
        run: yarn test

  static:
    runs-on: ubuntu-latest
    name: Slither run
    steps:
      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run analysis
        run: yarn test:slither
